### ISSUE TITLE
problems when installing SEQCROW in ChimeraX

### ISSUE THREAD

**Issue by JanJZhou** [QChASM/SEQCROW#10]
**Describe the bug**
When I trying to installing SEQCROW, there are always some problems reported

**To Reproduce**
1. Go to ChimeraX
2. Click on 'Tools'
3. Click on "More Tools"
4. Click on "SEQCROW"
5. Click on "Install"
6. The problems report

**the problems are copyed here**
Looking in indexes: https://pypi.org/simple, https://cxtoolshed.rbvi.ucsf.edu/pypi/ 
Processing c:\users\lenovo\downloads\seqcrow-1.6.3-py3-none-any.whl 
Requirement already satisfied: scipy in d:\chimerax\chimerax\bin\lib\site-packages (from SEQCROW==1.6.3) (1.9.3) 
Requirement already satisfied: psutil in d:\chimerax\chimerax\bin\lib\site-packages (from SEQCROW==1.6.3) (5.9.4) 
Requirement already satisfied: ChimeraX-Core=1.2 in d:\chimerax\chimerax\bin\lib\site-packages (from SEQCROW==1.6.3) (1.6.dev202303230759) 
Could not fetch URL https://pypi.org/simple/basis-set-exchange/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/basis-set-exchange/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) - skipping 
Could not fetch URL https://cxtoolshed.rbvi.ucsf.edu/pypi/basis-set-exchange/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='cxtoolshed.rbvi.ucsf.edu', port=443): Max retries exceeded with url: /pypi/basis-set-exchange/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) - skipping 
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) - skipping 
Could not fetch URL https://cxtoolshed.rbvi.ucsf.edu/pypi/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='cxtoolshed.rbvi.ucsf.edu', port=443): Max retries exceeded with url: /pypi/pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) - skipping 
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/basis-set-exchange/ 
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/basis-set-exchange/ 
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/basis-set-exchange/ 
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/basis-set-exchange/ 
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/basis-set-exchange/ 
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /pypi/basis-set-exchange/ 
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /pypi/basis-set-exchange/ 
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /pypi/basis-set-exchange/ 
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /pypi/basis-set-exchange/ 
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /pypi/basis-set-exchange/ 
ERROR: Could not find a version that satisfies the requirement basis-set-exchange (from seqcrow) (from versions: none) 
ERROR: No matching distribution found for basis-set-exchange

**Comment by ajs99778** [comment]
Thanks for reporting this. I am only able to reproduce this with older versions of ChimeraX. I'm not sure if it's a (now fixed)  ChimeraX bug with installing dependencies, or if there's some incompatibility with the basis-set-exchange module's dependencies and other ChimeraX modules. I'd recommend updating ChimeraX to the latest version (1.5 or a 1.6 daily build) and trying again. I'll do some more testing and modify the compatible ChimeraX versions in the next update.

**Comment by JanJZhou** [comment]
> Thanks for reporting this. I am only able to reproduce this with older versions of ChimeraX. I'm not sure if it's a (now fixed) ChimeraX bug with installing dependencies, or if there's some incompatibility with the basis-set-exchange module's dependencies and other ChimeraX modules. I'd recommend updating ChimeraX to the latest version (1.5 or a 1.6 daily build) and trying again. I'll do some more testing and modify the compatible ChimeraX versions in the next update.

Thanks for your help, I have tried another version (1.5) and fixed. :)
