### ISSUE TITLE
SEQCROW with ChimeraX 1.6.1

### ISSUE THREAD

**Issue by Cdc95** [QChASM/SEQCROW#11]
Hello,

I am unable to get SEQCROW to work with ChimeraX 1.6.1 on macOS 13.3.1 - I am not sure if I am doing something wrong, or if support just hasn't been added yet?

Thanks a bunch,
Colton

**Comment by ajs99778** [comment]
Colton,

Thanks for reporting this. It looks like the range of compatible ChimeraX versions just needed to be updated. The new version on the tool shed should fix this.
