### ISSUE TITLE
`xTB` Error processing trigger "job finished" path should be string, bytes, ...

### ISSUE THREAD

**Issue by MartinRJDagleish** [QChASM/SEQCROW#12]
Thank you very much for this superb extension for ChimeraX. I wanted to use the QM Input Generator for xTB, to optimize my 2D drawn input (I prefer xTB over AM1, PM6 or any other semi empirical calculation, because of speed and accuracy.) 

**Describe the bug**
When I use the QM Input Generator for xTB everything seems fine and the calculations also finish
successfully, but the problem I have, is that the output does not get opened up again after the calculation finsihed. 

Here I tried to put all windows together that are needed to reproduce. 
![image](https://github.com/QChASM/SEQCROW/assets/52655835/8fe474a8-4a85-4a5f-9466-e07bbc8c9cca)

**To Reproduce**
1. Goto QM Inputer Generator 
2. Use xTB for given strucuture and use GFN2-xTB 
3. Set "open structure" for "when finished"
4. After successful "job" get error

**Additional context**
I am not sure if that is the problem, but when I look into the scratch folder I see that the folder containing my calculation has spaces in it of the form: 
"Phosphan_test_opt Fri Sep 29 12.44.08 2023" 
![image](https://github.com/QChASM/SEQCROW/assets/52655835/33c7624d-00f1-4150-93ee-bf7cc01d3b13)

Could I be that the Python code does not support spaces in the path name for the folder? How can I change the folder name for the calculation?

**Comment by MartinRJDagleish** [comment]
@ajs99778 Thank you very much for the fast response. 

Please let me know if I can assist you in any way or if you need any more details. 
Otherwise I am hoping for a bugfix to fully utilize the extension to its full use.

**Comment by ajs99778** [comment]
I've uploaded a patch to the tool shed that should fix this bug

**Comment by MartinRJDagleish** [comment]
@ajs99778 Thank you very much! Sry I was on holiday the last few days and could not respond sooner, but the change fixes everything for xTB now :)

Thanks for the quick fix!
