### ISSUE TITLE
algorithm options for TS finding

### ISSUE THREAD

**Issue by joegair** [QChASM/SEQCROW#13]
It would be great if there was an option to turn on pre-optimization for nudged elastic band calculations via the SEQROW GUI. It would make sense to have a yes/no option under "TS search options > algorithm options".

Basically any structure that I draw in ChimeraX  for a NEB-TS job will require pre-optimization, especially when I'm manually manipulating a reactant structure into a product structure (to preserve atom numbering).

**Comment by ajs99778** [comment]
Easy enough to do. The next version will have a checkbox that will add `PreOpt True/False` to Orca's neb block.

**Comment by ajs99778** [comment]
toolshed version has been updated and now has this feature

**Comment by joegair** [comment]
Awesome! Thanks Tony!
