### ISSUE TITLE
Thorium (maybe other actinides) not supported

### ISSUE THREAD

**Issue by LaTruelle** [QChASM/SEQCROW#4]
**Describe the bug**
I cannot open a file containing a thorium atom.

**To Reproduce**
Open any Gaussian calculation with Th in it

**Expected behavior**
It should open!

**Screenshots**
![image](https://user-images.githubusercontent.com/1679586/176883327-7a77f155-1cee-4e5c-9ceb-36f4fdbc79a1.png)

It seems to be AaronTools based.

**Comment by ajs99778** [comment]
The version on the dev branch should be able to open these files: https://github.com/QChASM/SEQCROW/tree/dev

there's installation instructions if you scroll down to the readme. I'll make a few more changes before updating the toolshed version.

**Comment by LaTruelle** [comment]
Indeed, it works, thanks! I still get the error about the Radii from AaronTools, but I can at least open the files and plot orbitals.
