### ISSUE TITLE
Conformer generation with cREST not working

### ISSUE THREAD

**Issue by Leticia-maria** [QChASM/SEQCROW#5]
When I try to run conformer generation, it says it did not find the path for crest. Where and how do I define it on chimera X (I am using macOS)

**Comment by ajs99778** [comment]
The CREST executable path is specified in the "SEQCROW Jobs" tab of the ChimeraX settings. I think the settings on Mac are under the "Preferences" menu.

**Comment by ajs99778** [comment]
were you able to get this working?
