### ISSUE TITLE
Is there a way of visualizing xyz trajectories using SEQCROW on chimera x?

### ISSUE THREAD

**Issue by Leticia-maria** [QChASM/SEQCROW#6]
I have ran a conformational search with crest externally, but when I open the crest_conformers.xyz file, I do not see any place to get an animation of all the conformers.

**Comment by ajs99778** [comment]
Running the command `coordset slider <model ID>` (for example, `coordset slider #1`) will bring up the animation slider to flip through the conformers. The model ID is shown in the model panel.

The ChimeraX documentation for the coordset command is here: https://www.cgl.ucsf.edu/chimerax/docs/user/commands/coordset.html

**Comment by ajs99778** [comment]
There is now a ChimeraX plugin that will automatically run commands when a file is opened. Check it out here on the tool shed: https://cxtoolshed.rbvi.ucsf.edu/apps/chimeraxopencommands

You should be able to set it up so it runs `coordset slider #X` when you open a crest output file. There's more details on how to do this on the tool shed page. The plugin can be installed in probably the same way you installed seqcrow (Tools &rarr; More Tools... on the ChimeraX menu, go to the OpenCommands page and click install, and restart ChimeraX). 

Let me know if you need any help setting this up
