### ISSUE TITLE
Loading Cluster Growth Files

### ISSUE THREAD

**Issue by Cdc95** [QChASM/SEQCROW#8]
Hello,

Grimmes new QCG docking algorithm (https://doi.org/10.1021/acs.jctc.2c00239) produces an XYZ ensemble file (example attached below) where each structure has one more solvent molecule than the previous. To the best of my knowledge, there is currently no convenient way to load all of these structures. As such, I am just wondering if it would be possible to support loading this type of file? Maybe the extension 'growxyz' could be used to distinguish these files from other ensemble files?

Thanks a bunch,
Colton

[qcg_grow.txt](https://github.com/QChASM/SEQCROW/files/10923354/qcg_grow.txt)

**Comment by ajs99778** [comment]
Colton,

Do these files have an XYZ extension by default? The new XYZ parser in SEQCROW 1.5.11+ should load all the structures as different models if the elements or number of atoms changes from one structure to the next in the XYZ file. It's not possible in ChimeraX to have a structure change elements or number of atoms, so they have to be separate models.

ChimeraX has a built-in command [`mseries`](https://www.cgl.ucsf.edu/chimerax/docs/user/commands/mseries.html) that can flip through different models in a series. You should just be able to do something like `mseries slider #1` to open a slider to flip through the different structures. 

I could potentially make it so the `mseries` command is run by default if you open an XYZ file with a name like "qcg_grow". That should be relatively easy to do. I might also just update my new [OpenCommands](https://cxtoolshed.rbvi.ucsf.edu/apps/chimeraxopencommands) bundle to let users define these types of rules themselves. Currently, it will only run commands for the child models (i.e. #X.1-150) and not the parent (#X), so the `mseries` commands won't work with it. 

Best,

Tony

**Comment by ajs99778** [comment]
I've updated OpenCommands to allow commands to run for parent models. These criteria seem to work for me:
![image](https://user-images.githubusercontent.com/41082252/225521273-658268d4-b19f-4dcc-b09c-2dc4238c78cb.png)

There's installation instructions for OpenCommands here: https://github.com/ajs99778/ChimeraX_OpenCommands#installation and also more details on the tool shed page. Let me know if this fits with your workflow or if there's anything that would make these types of files easier to process.

**Comment by Cdc95** [comment]
Sorry for the late response - I must have missed the email for the first comment. That works perfectly!!

Thanks a bunch for all your help :) 
Colton
