### ISSUE TITLE
crest xyz energies

### ISSUE THREAD

**Issue by joegair** [QChASM/SEQCROW#9]
It would be really useful to have a plot of energy vs conformer number pop up when a crest_conformers.xyz file is opened. The same structure as the plot that opens for geometry optimizations would be ideal (plotting energy vs conformer number). 

The output would look something like this:

![Conformer Number vs Energy](https://user-images.githubusercontent.com/82832095/225653681-246ff577-2bcf-451c-b17a-8bed31f0135b.png)

It would be useful to plot energy relative to the lowest energy structure rather than absolute energy.

Just like the plot for geometry optimizations, it would be great to have a second tab that just gives the conformer number and relative energy. I like to use this tab for scrolling through lists of geometries using the down arrow rather than clicking on each point in the plot. 

Below is an example crest_conformers.xyz file. By default it contains geometries and energies, sorted from lowest energy structure to highest energy structure with energies in Hartree.

[crest_conformers.txt](https://github.com/QChASM/SEQCROW/files/10991425/crest_conformers.txt)

**Comment by ajs99778** [comment]
I've started working on this. I'd like to make it more general than just crest files, as I've seen other XYZ files with data in the comment line. Now when the plot opens, it shows any floating point number if finds in the comment lines. You'll have the choice to set the units of whatever the values are to Hartrees or kcal/mol. There's images of the plots below.

I think for plotting relative energies, I'll have it convert to kcal/mol. With Hartrees, the y-axis range looks jank (i.e. about the same as it currently looks). For what it's worth, when you hover over a point, it shows the energy in kcal/mol relative to the first point, which should be the lowest for crest.

If you want to test it out, you can install SEQCROW from GitHub. There's instructions for that here: https://github.com/QChASM/SEQCROW/tree/dev#installation

original
![image](https://user-images.githubusercontent.com/41082252/225807419-c980aa40-dce2-4093-8c46-2ea667bb8526.png)

after choosing Hartrees
![image](https://user-images.githubusercontent.com/41082252/225807434-89d376ee-ade9-437c-b6a8-d562616fe674.png)

**Comment by joegair** [comment]
This is fantastic! Generalizing to all xyz files is a great idea. Thank you!

**Comment by joegair** [comment]
Thanks so much for sharing this. I finally got around to trying it and it works exactly as I was hoping. 

I think there is a minor typo in the installation instructions.  You may want to change `toolshed install /path/to/SEQCROW-1.6.2-none-any.whl`, to `toolshed install /path/to/SEQCROW-1.6.2-py3-none-any.whl`

**Comment by ajs99778** [comment]
Thanks for pointing out the typo, it's fixed now. I've been a bit busy this week, but I just put the update with this on the ChimeraX tool shed. I changed the unit buttons to a combobox so more options can fit.
